version: '3.8'
services:
  app:
    image: ghcr.io/petroslobodenuik-ui/humanitarian-app:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
  # optional simple reverse proxy (Caddy) - uncomment if you want automatic HTTPS on a public host
  # caddy:
  #   image: caddy:2
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data

volumes:
  caddy_data: {}

# Notes:
# - This compose file is intended for production/Portainer: it references the image in GHCR.
# - For local development (build & mount), use the override file `docker-compose.dev.yml`:
#   docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build
