version: '3.8'
services:
  app:
    image: ghcr.io/petroslobodenuik-ui/humanitarian-app:latest
    restart: always
    ports:
      - "1188:8000"
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
